export const ACTION_TYPES={
    START_LOADING: "START_LOADING",
    END_LOADING: "END_LOADING",
    FETCH_POST: "FETCH_POST",
    FETCH_ALL: "FETCH_ALL",
    FETCH_BY_SEARCH: "FETCH_BY_SEARCH",
    CREATE: "CREATE",
    UPDATE: "UPDATE",
    DELETE:"DELETE",
    LIKE: "LIKE",
    AUTH: "AUTH",
    LOGOUT: "LOGOUT"
}